"""empty message

Revision ID: 625201d73684
Revises: 
Create Date: 2019-03-17 06:44:42.223420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625201d73684'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpside',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ourReference', sa.String(length=100), nullable=True),
    sa.Column('typeOfOperation', sa.String(length=100), nullable=True),
    sa.Column('commonReference', sa.String(length=100), nullable=True),
    sa.Column('contractdate', sa.String(length=100), nullable=True),
    sa.Column('randoma', sa.String(length=100), nullable=True),
    sa.Column('partyA', sa.String(length=100), nullable=True),
    sa.Column('partyB', sa.String(length=100), nullable=True),
    sa.Column('isdaDate', sa.String(length=100), nullable=True),
    sa.Column('valueDate', sa.String(length=100), nullable=True),
    sa.Column('exchangeRate', sa.String(length=100), nullable=True),
    sa.Column('buyQuant', sa.String(length=100), nullable=True),
    sa.Column('settlement1', sa.String(length=100), nullable=True),
    sa.Column('sellQuant', sa.String(length=100), nullable=True),
    sa.Column('deliveryAgent1', sa.String(length=100), nullable=True),
    sa.Column('intermediatery', sa.String(length=100), nullable=True),
    sa.Column('settlement2', sa.String(length=100), nullable=True),
    sa.Column('beneficiary2', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sgside',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ourReference', sa.String(length=100), nullable=True),
    sa.Column('typeOfOperation', sa.String(length=100), nullable=True),
    sa.Column('commonReference', sa.String(length=100), nullable=True),
    sa.Column('contractdate', sa.String(length=100), nullable=True),
    sa.Column('randoma', sa.String(length=100), nullable=True),
    sa.Column('partyA', sa.String(length=100), nullable=True),
    sa.Column('partyB', sa.String(length=100), nullable=True),
    sa.Column('isdaDate', sa.String(length=100), nullable=True),
    sa.Column('valueDate', sa.String(length=100), nullable=True),
    sa.Column('exchangeRate', sa.String(length=100), nullable=True),
    sa.Column('buyQuant', sa.String(length=100), nullable=True),
    sa.Column('settlement1', sa.String(length=100), nullable=True),
    sa.Column('sellQuant', sa.String(length=100), nullable=True),
    sa.Column('deliveryAgent1', sa.String(length=100), nullable=True),
    sa.Column('intermediatery', sa.String(length=100), nullable=True),
    sa.Column('settlement2', sa.String(length=100), nullable=True),
    sa.Column('beneficiary2', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sgside')
    op.drop_table('cpside')
    # ### end Alembic commands ###
